// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJF6R8wNo7iAko9FyHaxIGY4m7IM1JuAo',
    appId: '1:597347404405:web:c622cbd34498f0235cc63c',
    messagingSenderId: '597347404405',
    projectId: 'firestoredb-35174',
    authDomain: 'firestoredb-35174.firebaseapp.com',
    storageBucket: 'firestoredb-35174.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3rc2ALQGk-5MH_RWQdJ9n9cLg85uQ5eQ',
    appId: '1:597347404405:android:0b95c94a17b726355cc63c',
    messagingSenderId: '597347404405',
    projectId: 'firestoredb-35174',
    storageBucket: 'firestoredb-35174.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi71jG4Fy-XCnl4OoQXl6R6kkw611hP20',
    appId: '1:597347404405:ios:5c87756e3dec1c9d5cc63c',
    messagingSenderId: '597347404405',
    projectId: 'firestoredb-35174',
    storageBucket: 'firestoredb-35174.appspot.com',
    iosClientId: '597347404405-0fco9i1l2o9f24vvrolec5nj03cir25l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi71jG4Fy-XCnl4OoQXl6R6kkw611hP20',
    appId: '1:597347404405:ios:5c87756e3dec1c9d5cc63c',
    messagingSenderId: '597347404405',
    projectId: 'firestoredb-35174',
    storageBucket: 'firestoredb-35174.appspot.com',
    iosClientId: '597347404405-0fco9i1l2o9f24vvrolec5nj03cir25l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirestore',
  );
}
